apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: helm-stack
  source:
    repoURL: https://github.com/ArunBrainScale/helm-tools.git
    targetRevision: HEAD
    path: helm-charts
  destination:
    server: https://kubernetes.default.svc
    namespace: helm-stack
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true