apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: helm-stack
  source:
    path: kubernetes
    repoURL: https://github.com/ThorstenHans/aks-cluster-scaling-demo
    targetRevision: HEAD
    # helm:
    #   values: |
    #     prometheus:
    #       ingress:
    #         enabled: true
    #         annotations: {kubernetes.io/ingress.class: "nginx"}
    #         hosts: ["prometheus.example.com"]
    #         paths: ["/prometheus"]
    #   version: v3
  destination:
    namespace: demo-app
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true